[env:esp32-c6-devkitm-1]
platform = espressif32
board = esp32-c6-devkitm-1
framework = espidf
board_upload.flash_size = 4MB
board_build.partitions = partitions_singleapp_large.csv
monitor_speed = 115200